@url = http://localhost:5000

###
GET {{url}}

###
GET {{url}}/reservations

###
POST {{url}}/reservations
Content-Type: application/json

{
    "EmployeeName": "John Doe",
    "ParkingSpotName": "P1",
    "LicensePlate": "XYZ123",
    "Date": "2022-10-01"
}

###
PUT {{url}}/reservations   